import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const METHODOLOGY_TEMPLATE_PATH = path.resolve(
  __dirname,
  "../../..",
  "data",
  "templates",
  "ad-delivery-plan-methodology.html",
);

export interface InjectorOptions {
  activeSkillName?: string;
}

function isAdPlanHtml(filePath: string, content: string, activeSkillName?: string): boolean {
  if (!filePath.toLowerCase().endsWith(".html")) return false;
  if (activeSkillName === "ad-delivery-plan") return true;
  // Fallback heuristic for HTML generated by other skills (e.g. guizang) for an ad plan
  const hasPlan = content.includes("投流方案");
  const hasCompetitor = content.includes("竞品分析");
  const hasFramework = content.includes("context = 角度 × 人群") || content.includes("定向框架");
  return hasPlan && (hasCompetitor || hasFramework);
}

function findSlideCommentIndices(html: string): { index: number; number: number; title: string }[] {
  const regex = /<!-- Slide (\d+):\s*([^>]+?) -->/g;
  const results: { index: number; number: number; title: string }[] = [];
  let match: RegExpExecArray | null;
  while ((match = regex.exec(html)) !== null) {
    results.push({ index: match.index, number: parseInt(match[1], 10), title: match[2].trim() });
  }
  return results;
}

function findInsertionIndex(html: string): number | null {
  const comments = findSlideCommentIndices(html);

  // Preferred anchor: 行业趋势 / 行业情报
  const industryIdx = comments.findIndex(
    (c) => c.title.includes("行业趋势") || c.title.includes("行业情报"),
  );
  if (industryIdx !== -1 && industryIdx + 1 < comments.length) {
    return comments[industryIdx + 1].index;
  }
  if (industryIdx !== -1) {
    // Last slide is industry info: append at end
    return html.length;
  }

  // Fallback anchor: 竞品分析
  const competitorIdx = comments.findIndex((c) => c.title.includes("竞品分析"));
  if (competitorIdx !== -1 && competitorIdx + 1 < comments.length) {
    return comments[competitorIdx + 1].index;
  }
  if (competitorIdx !== -1) {
    return html.length;
  }

  return null;
}

function renumberComments(html: string): string {
  const regex = /<!-- (?:Slide \d+|METHODOLOGY_SLIDE):\s*([^>]+?) -->/g;
  let counter = 0;
  return html.replace(regex, (_match, title: string) => {
    counter += 1;
    return `<!-- Slide ${counter}: ${title.trim()} -->`;
  });
}

function renumberMethNumbers(fragment: string, startNumber: number): string {
  let counter = startNumber;
  return fragment.replace(/M(\d{2})/g, () => {
    const num = counter;
    counter += 1;
    return String(num).padStart(2, "0");
  });
}

function appendRenumberScript(html: string): string {
  const script = `
<script>
(function() {
  var deck = document.getElementById('deck') || document.querySelector('.deck');
  if (!deck) return;
  var slides = deck.querySelectorAll('.slide');
  slides.forEach(function(slide, idx) {
    var num = idx + 1;
    ['.slide-number', '.page-num', '.meth-number'].forEach(function(sel) {
      var el = slide.querySelector(sel);
      if (el) el.textContent = String(num).padStart(2, '0');
    });
  });
})();
</script>`;
  // Insert before closing </body> if present, otherwise before closing </html>
  if (html.includes("</body>")) {
    return html.replace("</body>", script + "\n</body>");
  }
  if (html.includes("</html>")) {
    return html.replace("</html>", script + "\n</html>");
  }
  return html + script;
}

export function injectAdPlanMethodology(
  filePath: string,
  content: string,
  opts: InjectorOptions = {},
): { content: string; injected: boolean } {
  if (!isAdPlanHtml(filePath, content, opts.activeSkillName)) {
    return { content, injected: false };
  }

  if (!fs.existsSync(METHODOLOGY_TEMPLATE_PATH)) {
    console.error("[adPlanMethodologyInjector] 模板文件不存在:", METHODOLOGY_TEMPLATE_PATH);
    return { content, injected: false };
  }

  const fragment = fs.readFileSync(METHODOLOGY_TEMPLATE_PATH, "utf-8");

  // Avoid double-injection
  if (content.includes('class="slide methodology-slide"') || content.includes("METHODOLOGY_SLIDE")) {
    return { content, injected: false };
  }

  let insertionIndex = findInsertionIndex(content);
  let before: string;
  let after: string;
  let methodologyStartNumber = 1;

  if (insertionIndex === null) {
    // Fallback: insert before the closing deck container
    const bodyClose = content.lastIndexOf("</body>");
    const deckClose = bodyClose > 0 ? content.lastIndexOf("</div>", bodyClose) : content.lastIndexOf("</div>");
    if (deckClose <= 0) {
      console.error("[adPlanMethodologyInjector] 未找到 deck 容器，无法注入");
      return { content, injected: false };
    }
    before = content.slice(0, deckClose);
    after = content.slice(deckClose);
    methodologyStartNumber = 1;
  } else {
    before = content.slice(0, insertionIndex);
    after = content.slice(insertionIndex);
    // Determine the starting slide number for methodology pages based on preceding slides
    const precedingComments = findSlideCommentIndices(before);
    if (precedingComments.length > 0) {
      methodologyStartNumber = precedingComments[precedingComments.length - 1].number + 1;
    }
  }

  const numberedFragment = renumberMethNumbers(fragment, methodologyStartNumber);
  let newContent = before + "\n" + numberedFragment + "\n" + after;
  newContent = renumberComments(newContent);
  newContent = appendRenumberScript(newContent);

  return { content: newContent, injected: true };
}
